### ISSUE TITLE
intermittent errors when run on vsts build agent

### ISSUE THREAD

**Issue by stombeur** [sandorfr/gulp-swagger-generator#37]
Locally, the gulp swagger task runs fine, but half of the time the build running on a vsts (visual studio online) build agent fails with this error

2016-11-07T16:01:38.9312110Z [16:01:38] ["definitions","definitionsMap","operations","host","basePath","defaultConsumes","defaultProduces"]
2016-11-07T16:01:38.9322105Z [16:01:38] ["ArgumentInterface","Client","Definition","Interface","Mock","SingleFile","Type","Typing","languageOptions"]
2016-11-07T16:01:38.9902093Z [16:01:38] ["ArgumentInterface","Client","Definition","Interface","Mock","SingleFile","Type","Typing","languageOptions"]
2016-11-07T16:01:39.1242111Z Unhandled rejection TypeError: Cannot read property 'map' of undefined
2016-11-07T16:01:39.1242111Z     at pascalCasePreserve (C:\a\1\s\src\Avola.Front.UI\node_modules\gulp-swagger-generator\lib\index.js:179:17)
2016-11-07T16:01:39.1242111Z     at TypescriptType.<anonymous> (C:\a\1\s\src\Avola.Front.UI\node_modules\gulp-swagger-generator\lib\index.js:141:16)
2016-11-07T16:01:39.1242111Z     at eval (eval at createFunctionContext (C:\a\1\s\src\Avola.Front.UI\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:5:100)
2016-11-07T16:01:39.1242111Z     at prog (C:\a\1\s\src\Avola.Front.UI\node_modules\handlebars\dist\cjs\handlebars\runtime.js:219:12)
2016-11-07T16:01:39.1252113Z     at TypescriptType.<anonymous> (C:\a\1\s\src\Avola.Front.UI\node_modules\handlebars\dist\cjs\handlebars\helpers\block-helper-missing.js:13:14)
2016-11-07T16:01:39.1252113Z     at eval (eval at createFunctionContext (C:\a\1\s\src\Avola.Front.UI\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:9:48)
2016-11-07T16:01:39.1252113Z     at Object.prog [as fn] (C:\a\1\s\src\Avola.Front.UI\node_modules\handlebars\dist\cjs\handlebars\runtime.js:219:12)
2016-11-07T16:01:39.1252113Z     at Property.<anonymous> (C:\a\1\s\src\Avola.Front.UI\node_modules\gulp-swagger-generator\lib\index.js:154:28)
2016-11-07T16:01:39.1252113Z     at Object.eval (eval at createFunctionContext (C:\a\1\s\src\Avola.Front.UI\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:5:94)
2016-11-07T16:01:39.1252113Z     at main (C:\a\1\s\src\Avola.Front.UI\node_modules\handlebars\dist\cjs\handlebars\runtime.js:173:32)
2016-11-07T16:01:39.1252113Z     at ret (C:\a\1\s\src\Avola.Front.UI\node_modules\handlebars\dist\cjs\handlebars\runtime.js:176:12)
2016-11-07T16:01:39.1252113Z     at ret (C:\a\1\s\src\Avola.Front.UI\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:525:21)
2016-11-07T16:01:39.1252113Z     at Object.invokePartial (C:\a\1\s\src\Avola.Front.UI\node_modules\handlebars\dist\cjs\handlebars\runtime.js:268:12)
2016-11-07T16:01:39.1252113Z     at Object.invokePartialWrapper [as invokePartial] (C:\a\1\s\src\Avola.Front.UI\node_modules\handlebars\dist\cjs\handlebars\runtime.js:68:39)
2016-11-07T16:01:39.1252113Z     at eval (eval at createFunctionContext (C:\a\1\s\src\Avola.Front.UI\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:10:28)
2016-11-07T16:01:39.1252113Z     at prog (C:\a\1\s\src\Avola.Front.UI\node_modules\handlebars\dist\cjs\handlebars\runtime.js:219:12)

**Comment by stombeur** [comment]
looks like I was able to fix it.
The problem is when running multiple swaggergenerator tasks. If you don't make absolutely sure that they run sequentially (e.g. by splitting up in multiple tasks, returning the stream in each task and running them inside a seq) then on slower disks, there is some locking of files in handlebars I guess.
So if you use gulp _correctly_ ;-) then this is not an issue

**Comment by asiffermann** [comment]
Hi @stombeur ! Glad to know you did manage to fix your issue :)

**Comment by sandorfr** [comment]
@stombeur parallel build in the same process has not been tested I can guess from there why it's not working. That being said I think it's not going to be an issue in the vnext I'm working on.
